import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';

import { ModalProvider } from './contexts/ModalContext';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Natal Smartphones',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className='scroll-smooth'>
      <body
        className={`${raleway.variable} antialiased overflow-x-hidden w-dvw`}
      >
        <ModalProvider>
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
